services:
  backend-container:
    build:
      context: ./Backend
    ports:
      - "9000:443"
    volumes:
      - ${PWD}/Database:/skillseek-backend/Database
    container_name: backend-container
    image: mirotivo/skillseek-backend-container:latest

  frontend-container:
    depends_on:
      - backend-container
    build:
      # context: ./Frontend
      context: ./Frontend.Angular
    ports:
      - "8080:80"
      - "8000:443"
    container_name: frontend-container
    image: mirotivo/skillseek-frontend-container:latest

  # prometheus:
  #   depends_on:
  #     - backend-container
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   container_name: prometheus

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   container_name: grafana
